[package]
name = "wasm_gui"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.30.0"
egui = "0.30.0"
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
env_logger = "0.10"